/* 
=====================================================
Magnitude Analysis
=====================================================
Comparing the measure values by categories
Helps us understand the importance of different categories
Formula: SUM/AVG/COUNT [Measure] By [Dimension]
=====================================================
*/

-- Finding the total number of customers by country
SELECT 
	country,
	COUNT(customer_key) total_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC;
GO

-- Finding the total number of customers by gender
SELECT 
	gender,
	COUNT(customer_key) total_customers 
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_key) DESC;
GO

-- Finding the total number of product by category
SELECT 
	category,
	COUNT(product_name) total_products 
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;
GO

-- Finding the average cost in each category?
SELECT 
	category,
	AVG(cost) average_cost 
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;
GO

-- Finding the total revenue generated for each category?
SELECT 
	p.category,
	SUM(s.sales_amount) total_revenue_by_category 
FROM gold.fact_sales s 
LEFT JOIN gold.dim_products p
ON P.product_key = s.product_key
GROUP BY category
ORDER BY total_revenue_by_category DESC;
GO

-- Finding the total revenue generated by each customers
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) total_revenue_by_customer 
FROM gold.fact_sales s 
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.product_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue_by_customer DESC;
GO

-- Finding the distribution of sold items across countries?
SELECT 
	c.country,
	SUM(f.quantity) total_items_sold
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.product_key
GROUP BY country
ORDER BY total_items_sold DESC;
GO
